src/utils/gitHubUtils.ts
vscode.proposed.d.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/103

Use new proposed GitHub api changes

---

package.json
src/commands/createHttpFunction.ts

Remove dependency, prompt to install

---

src/commands/createStaticWebApp/GitHubRepoListStep.ts
src/commands/createStaticWebApp/RepoCreateStep.ts
src/utils/gitHubUtils.ts

Partial fix to https://github.com/microsoft/vscode-azurestaticwebapps/issues/106
Still need to do the other part, which is verify if there is a branch or not when selecting an empty repo.

Create new repo in org selected

---

src/commands/createStaticWebApp/StaticWebAppCreateStep.ts
src/commands/createStaticWebApp/createStaticWebApp.ts
src/tree/StaticWebAppTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/104
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/74
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/105

Add/update some output for creating/deleting 📤

---

src/tree/FunctionsTreeItem.ts

Add tree item for when there are no functions

---

src/commands/createHttpFunction.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/139

Validate trigger 🔫 names

---

src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/148

Add verifyProvider step

---

package.json

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/171
Actions tree item wasn't supposed to have a view properties as it doesn't have a data property.

Correct the regexp

---

src/commands/createStaticWebApp/addWorkspaceTelemetry.ts
src/tree/SubscriptionTreeItem.ts

Some telemetry about the user's workspace so we can better understand how users are creating static web apps.

Add telemetry about users configuration

---

src/commands/createHttpFunction.ts
src/commands/deleteEnvironment.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/174

suppress report issues on intentional errors

---

src/commands/github/actionCommands.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/205

Suppress create pick for action commands

---

src/commands/createStaticWebApp/GitHubRepoListStep.ts
src/commands/createStaticWebApp/IStaticWebAppWizardContext.ts
src/tree/EnvironmentTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/gitHubUtils.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/19
This further reduces the basic create prompts by 1.  I think that realistically, this is as small as we'll get until we can reliably detect the location of the app/api folders.
I don't see other extensions that have advanced create in the wizardContext, but it seemed unavoidable to me. 😐

Use default branch for basic create scenario

---

package.nls.json
src/commands/createStaticWebApp/createStaticWebApp.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/238

Change text to Show Action in GitHub

---

src/tree/SubscriptionTreeItem.ts
src/utils/gitHubUtils.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/237

Swallow VS Code 'User did not consent' error and throw UserCancelledError

---

src/commands/createStaticWebApp/EnterApiLocationStep.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/182

Improve enter api location wording

---

src/commands/createRepo/RepoNameStep.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/206

Add message saying special characters get replaced

---

src/commands/createRepo/WorkspaceListStep.ts
src/commands/createStaticWebApp/StaticWebAppNameStep.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/268
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/267

Generate name properly for basic create when repo is detected and set remoteName if no origin is detected

---

package-lock.json
package.json
src/commands/appSettings/AppSettingsClient.ts
src/commands/appSettings/downloadAppSettings.ts
src/commands/appSettings/uploadAppSettings.ts
src/commands/createRepo/RepoCreateStep.ts
src/commands/createRepo/RepoNameStep.ts
src/commands/createStaticWebApp/GitHubBranchListStep.ts
src/commands/createStaticWebApp/GitHubOrgListStep.ts
src/commands/createStaticWebApp/GitHubRepoListStep.ts
src/commands/github/actionCommands.ts
src/commands/github/createOctokitClient.ts
src/commands/registerCommands.ts
src/tree/ActionTreeItem.ts
src/tree/ActionsTreeItem.ts
src/tree/EnvironmentTreeItem.ts
src/tree/FunctionsTreeItem.ts
src/tree/JobTreeItem.ts
src/tree/StaticWebAppTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/azureClients.ts
src/utils/azureUtils.ts
src/utils/gitHubUtils.ts
test/global.test.ts

Includes lazy loading azure packages and passing context along as discussed [here](https://github.com/microsoft/vscode-azurestaticwebapps/pull/253#discussion_r524528414)

Bump shared packages

---

package.json
package.nls.json
src/commands/registerCommands.ts

Use "Report Issue" command

---

src/commands/createRepo/RepoNameStep.ts
src/commands/createStaticWebApp/GitHubOrgListStep.ts
src/commands/createStaticWebApp/GitHubRepoListStep.ts
src/commands/createStaticWebApp/StaticWebAppNameStep.ts

Related to https://github.com/microsoft/vscode-azuretools/pull/824

Use valuesToMask for create swa wizard

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts
src/extensionVariables.ts
src/utils/azureUtils.ts

Fixes #327 
Think it's worth downgrading npm so my package lock doesn't go crazy like this?

Updates for experimental service

---

package-lock.json
package.json
src/commands/openYAMLConfigFile.ts
src/tree/EnvironmentTreeItem.ts
src/tree/localProject/ConfigGroupTreeItem.ts
src/tree/localProject/ConfigTreeItem.ts
src/tree/localProject/LocalProjectTreeItem.ts
src/utils/gitHubUtils.ts
src/utils/yamlUtils.ts

Move ConfigGroupTreeItem under EnvironmentTreeItem and make ConfigTreeItems clickable

---

package.json

Related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/97
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/98

Add staticwebapp.config.json schema

---

src/extension.ts
src/tree/AzureAccountTreeItemWithProjects.ts

The local project tree item has been stripped down and it this point it doesn't even render any children. So I don't think it should show up even with the feature flag enabled

Never show local project tree item

---

src/commands/createStaticWebApp/StaticWebAppNameStep.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/232

Add related name task for adv. create

---

src/commands/createHttpFunction.ts
src/getExtensionApi.ts
src/vscode-azurefunctions.api.d.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/323
Relies on Functions releasing with https://github.com/microsoft/vscode-azurefunctions/pull/2773/files/4908212f6e918ac7e207a016d5aff1107830ff88..bcde4acbd2131dddde8d42b99e238754cad7376b merged

Use new functions api to select .NET3

---

package.json
package.nls.json
src/constants.ts
src/tree/EnvironmentTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/365

Remove local project feature flag

---

src/commands/appSettings/AppSettingsClient.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/220
| Old | New |
|-|-|
|![Screen Shot 2021-05-03 at 5 41 04 PM](https://user-images.githubusercontent.com/22795803/116949409-ebd8d680-ac36-11eb-854b-73f40d40e28f.png)|![Screen Shot 2021-05-03 at 5 40 35 PM](https://user-images.githubusercontent.com/22795803/116949403-e7142280-ac36-11eb-9b92-c75db0a05194.png)|

Include environment info in notification message when uploading/downloading app settings

---

package-lock.json
package.json
package.nls.json
src/commands/createSwaConfigFile.ts
src/commands/registerCommands.ts
src/utils/workspaceUtils.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/97

Add 'Create SWA Config File' command

---

src/tree/EnvironmentTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/371

Sort EnvironmentTreeItem children

---

src/commands/github/cloneRepo.ts
src/gitHubTypings.ts
src/utils/gitHubUtils.ts
src/utils/gitUtils.ts
src/utils/workspaceUtils.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/329

Add 'create fork' option if user doesn't have admin rights

---

src/commands/createStaticWebApp/createStaticWebApp.ts

Add 'View/Edit Config' button to SWA create notification

---

src/commands/createStaticWebApp/createStaticWebApp.ts
src/commands/showSwaCreated.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/385

Add telemetry for prompt after create

---

src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/406

Check remote to determine whether or not we should create a repo

---

src/utils/gitUtils.ts

Resolves this comment https://github.com/microsoft/vscode-azurestaticwebapps/pull/407/files#r645036607

Don't alter original gitWorkspace when verifying

---

src/commands/createStaticWebApp/postCreateStaticWebApp.ts

I was seeing the error "Cannot find StaticSite with name ---" commonly enough in telemetry from `postCreateStaticWebApp`.  Users shouldn't even be seeing this error in the first place, but I believe that it's probably due to a timing issue (since this should be created by this point).

Try catch the call to Azure

---

package-lock.json
package.json
src/commands/createRepo/RemoteShortnameStep.ts
src/commands/createRepo/RepoCreateStep.ts
src/commands/createRepo/RepoNameStep.ts
src/commands/createRepo/RepoPrivacyStep.ts
src/commands/createStaticWebApp/ApiLocationStep.ts
src/commands/createStaticWebApp/AppLocationStep.ts
src/commands/createStaticWebApp/BuildPresetListStep.ts
src/commands/createStaticWebApp/GitHubOrgListStep.ts
src/commands/createStaticWebApp/OutputLocationStep.ts
src/commands/createStaticWebApp/SkuListStep.ts
src/commands/createStaticWebApp/StaticWebAppCreateStep.ts
src/commands/createStaticWebApp/StaticWebAppNameStep.ts
src/commands/createStaticWebApp/addLocationTelemetry.ts
src/commands/createStaticWebApp/setWorkspaceContexts.ts
src/commands/createSwaConfigFile.ts
src/commands/deleteEnvironment.ts
src/commands/deleteStaticWebApp.ts
src/commands/openYAMLConfigFile.ts
src/extension.ts
src/extensionVariables.ts
src/getExtensionApi.ts
src/tree/GitHubConfigGroupTreeItem.ts
src/utils/gitUtils.ts
src/utils/workspaceUtils.ts
src/utils/yamlUtils.ts
test/global.test.ts
test/selectBuildConfigs.test.ts

Same as microsoft/vscode-azurestorage#987

Use action-specific user input and standardize name of context

---

src/commands/openYAMLConfigFile.ts
src/commands/showSwaCreated.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/442

Change references of config to workflow

---

README.md

Found this doc page and thought it would be useful to have on the readme.

Add link to recommended settings for popular frameworks

---

package-lock.json
package.json
src/commands/appSettings/AppSettingsClient.ts
src/commands/appSettings/downloadAppSettings.ts
src/commands/appSettings/uploadAppSettings.ts
src/commands/openInPortal.ts
src/commands/registerCommands.ts
src/tree/ActionTreeItem.ts
src/tree/ActionsTreeItem.ts
src/tree/EnvironmentTreeItem.ts
src/tree/FunctionTreeItem.ts
src/tree/FunctionsTreeItem.ts
src/tree/IAzureResourceTreeItem.ts
src/tree/JobTreeItem.ts
src/tree/StaticWebAppTreeItem.ts
src/tree/StepTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/azureClients.ts
src/utils/azureUtils.ts

See https://github.com/microsoft/vscode-azuretools/pull/963 and https://github.com/microsoft/vscode-azuretools/pull/964 for more info

Bump shared packages to support correlation id

---

src/commands/createStaticWebApp/SkuListStep.ts
src/constants.ts

Add details about pricing options

---

src/commands/createStaticWebApp/createStaticWebApp.ts
src/commands/createStaticWebApp/setWorkspaceContexts.ts
src/constants.ts
src/utils/workspaceUtils.ts

Needed to refactor this for the create from template feature in a future PR. You can see how these changes are used with the create from template feature in the `alex/createFromTemplate` branch.
[Preview the PR that depends on this refactor](https://github.com/microsoft/vscode-azurestaticwebapps/compare/alex/refactorGetWorkspaceFolder...alex/createFromTemplate?expand=1)

Refactor getWorkspaceFolder

---

src/commands/openYAMLConfigFile.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/501

Use Uri.file rather than Uri.parse for creating Uri from yaml file path

---

package.json
src/tree/ActionTreeItem.ts
src/tree/EnvironmentTreeItem.ts
src/tree/JobTreeItem.ts

Fixes #499
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/500

Add Job and Step TreeItems context value to jump straight to actions tree

---

src/commands/cli/validateSwaCliIsLatest.ts

Was going through telemetry and noticed this. Oops!

Fix telemetry property name

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1016
Fixes #530

Change location step placeholder

---

src/cli/SwaCliTaskProvider.ts

This will now actually invoke the swa cli.

Fix swa config tasks

---

src/debug/StaticWebAppDebugProvider.ts

Adding a few properties here so we can see how much debugging is being used. As well as % users with api, or swa-cli.config.json when debugging.

Add telemetry to resolve debug config

---

src/cli/SwaCliTaskProvider.ts
src/debug/StaticWebAppDebugProvider.ts

Also includes 9126a3d1e8cf11290f761e5ac785ffb2a21a3fcd from #565, but that will "go away" when #565 is merged.

Add telemetry for debug and task providers

---

src/commands/createHttpFunction.ts
src/getExtensionApi.ts
src/vscode-azurefunctions.api.d.ts

Depends on https://github.com/microsoft/vscode-azurefunctions/pull/3031 
Fixes #590

Support creating .NET 6 functions

---

src/commands/deleteEnvironment.ts

Thought this was a great suggestion. 
Fixes #591

Specify "environment" in confirm delete modal

---

src/commands/deleteStaticWebApp.ts

Add "static web app" to delete confirmation

---

src/tree/SubscriptionTreeItem.ts

Fixes #558 
Might need feedback on the wording, "No available regions."

Add message for when no locations are found

---

package-lock.json
package.json
src/tree/StaticWebAppTreeItem.ts
src/utils/azureClients.ts

Fixes #594 
Important to see this [comment](https://github.com/microsoft/vscode-azurestaticwebapps/pull/596/files#diff-df419a970c68bdec8ae31d33c884c0d08604f4273a8b5e3001a5fc32fe425a90R103) about some weird behavior I found when listing the resources in the RG before deleting.

Delete resource group when deleting swa

---

src/debug/StaticWebAppDebugProvider.ts

Use RegExp match to find Functions debug config

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts
src/utils/azureUtils.ts

Show friendly error for unsupported clouds

---

package.json

Corresponding to https://github.com/microsoft/vscode-azureresourcegroups/pull/126.

Change to use contribution point for activation

---

package-lock.json
package.json

Bump appservice package to fix CVE-2022-24066

---

package.json
package.nls.json

Change refresh command to use azureResource

---

package-lock.json
package.json
src/tree/EnvironmentTreeItem.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1133
Fixes #672

Fix duplicate app settings context menu items

---

package-lock.json
package.json
src/commands/deleteStaticWebApp/IDeleteWizardContext.ts
src/commands/deleteStaticWebApp/deleteStaticWebApp.ts
src/tree/StaticWebAppTreeItem.ts

Use deleteTreeItemImpl to fix #668

---

package-lock.json
package.json
src/commands/appSettings/downloadAppSettings.ts
src/commands/appSettings/editAppSetting.ts
src/commands/appSettings/renameAppSetting.ts
src/commands/appSettings/uploadAppSettings.ts
src/commands/browse.ts
src/commands/createChildNode.ts
src/commands/deleteEnvironment.ts
src/commands/deleteNode.ts
src/commands/deleteStaticWebApp/deleteStaticWebApp.ts
src/commands/github/actionCommands.ts
src/commands/github/cloneRepo.ts
src/commands/github/jobLogs/openGitHubLog.ts
src/commands/github/openGitHubRepo.ts
src/commands/github/showActions.ts
src/commands/openInPortal.ts
src/commands/openYAMLConfigFile.ts
src/commands/registerCommands.ts
src/commands/viewProperties.ts
src/constants.ts
src/tree/EnvironmentTreeItem.ts
src/utils/contextUtils.ts

Change all commands to the pickAppResource function added by https://github.com/microsoft/vscode-azureresourcegroups/pull/212
Depends on https://github.com/microsoft/vscode-azureresourcegroups/pull/212, and https://github.com/microsoft/vscode-azuretools/pull/1141

Fix app settings commands from command palette

---

package-lock.json
package.json
package.nls.json

Depends on https://github.com/microsoft/vscode-azureresourcegroups/pull/242
Part of fixing https://github.com/microsoft/vscode-azureresourcegroups/issues/214

Add detail to create static web app command

---

package-lock.json
package.json

Depends on https://github.com/microsoft/vscode-azureresourcegroups/pull/245

Use workspace submenu

---

NOTICE.html
package-lock.json
package.json

I guess my first PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/686 didn't do it properly. This has all the commits, but the only changed file is the NOTICE.html

Merge main into unified

---

package-lock.json
package.json
src/commands/createStaticWebApp/BuildPresetListStep.ts

Disable Next.js (SSR)

---

package-lock.json
package.json
src/cli/SwaCliTaskProvider.ts
src/commands/cli/swaCliTask.ts
src/vsCodeConfig/tasks.ts

Fix debug task shell quoting

---

src/buildPresets/buildPresets.ts

Default values based on https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs
Fixes #732

Add Nuxt 3 build preset

---

src/commands/createStaticWebApp/BuildPresetListStep.ts

Show Next.JS SSR preset

---

src/commands/openYAMLConfigFile.ts

Fixing some incorrect logic added in the initial v1.5 migration.
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/780

Fix edit workflow command when invoked from palette

---

src/StaticWebAppResolver.ts
src/tree/StaticWebAppTreeItem.ts

https://github.com/microsoft/vscode-azurestaticwebapps/issues/805

Suppress not github repo error

---

src/buildPresets/buildPresets.ts
src/getExtensionApi.ts

Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/789
Also noticed an GIT API bug because the else was on the wrong if clause

Add SvelteKid to build preset

---

.azure-pipelines/common/package.yml

Follows this implementation: https://github.com/microsoft/vscode-azureresourcegroups/pull/648/files

Add build def to name

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json

https://github.com/microsoft/azcode-internal/issues/5

Bump version, update changelog, and update notice

---

README.md

related: https://github.com/microsoft/azcode-internal/issues/5

Add vscode.dev blurb to readme

---

src/buildPresets/buildPresets.ts

Add HTML preset

---

package-lock.json
package.json
src/commands/deleteStaticWebApp/IDeleteWizardContext.ts

The v2 versions of these packages are fully migrated to Track 2 SDKs.

Update shared packages to v2

---

src/tree/EnvironmentTreeItem.ts

Fix detecting linked environments

---

src/commands/createStaticWebApp/createStaticWebApp.ts

Fixes the create command when called from the workspace menu when workspace items may have been selected.

Fix create command when workspace items are selected

---

package.json

Partially fixes https://github.com/microsoft/vscode-azurefunctions/issues/3783

Add light and dark paths for submenu icon

---

package-lock.json
package.json

Hopefully should fix it so the build passes again

Upgrade `@vscode/test-electron`
