package.json, package.nls.json, src/commands/openGitHubRepo.ts, src/commands/registerCommands.ts, src/commands/viewGitHubRepo.ts, src/tree/EnvironmentTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/95
Rather than just taking the user to the attached repo, I added the branch information so it'd open the site with that specific branch up.  I think that's actually a little more useful (especially since the command exists on each environment)
=> Add command to view GitHub repo/branch

src/commands/createStaticWebApp/AppLocationStep.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/91
The default value is now '/', signifying the root.  I updated the message to include the tool tip the portal provides for clarity, since I think it's not super intuitive anyway.
=> Conform our default value to portal

package.json, package.nls.json, src/commands/createStaticWebApp/createStaticWebApp.ts, src/commands/github/cloneRepo.ts, src/commands/github/openGitHubRepo.ts, src/commands/github/showActions.ts, src/commands/registerCommands.ts
Fixes #33 
There were enough GitHub specific actions that I think it's worth throwing them in their own folder.  None of those files were edited besides their imports.
I'm reconsidering where we have this on the context menu...  Today it looks like this
I made the choice to have Open Repo in Github exist on the Environment (rather than the Static Web App) because I can open it to the _specific_ branch that they have configured to the app.
Clone and Actions don't have that level of granularity, the target is the repo itself.  But I feel like there's a weird split of where the context action menu items are.  Thoughts?
=> Add git clone 👨🏼‍🤝‍👨🏼 to static web app

src/commands/appSettings/editAppSetting.ts, src/commands/appSettings/renameAppSetting.ts, src/commands/appSettings/uploadAppSettings.ts, src/commands/deleteStaticWebApp.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/110
I thought about fixing this by just calling deleteNode and putting the confirmation in StaticTreeItem.deleteTreeItemImpl, but then you have the deleting spinner on the treeItem before the confirmation box.  I feel like that this is a manageable solution for now.
I might make a new function that calls deleteNode, but is called deleteNodeWithConfirm or something like that to be used for Static Web Apps and eventually Environments.
Also suppressing edit, rename, and upload made sense to me.
=> add SuppressCreatePick ⛏ to treePickers 🌲⛏

package.json, package.nls.json, src/commands/createStaticWebApp/ApiLocationStep.ts, src/commands/createStaticWebApp/AppArtifactLocationStep.ts, src/commands/createStaticWebApp/AppLocationStep.ts, src/commands/createStaticWebApp/IStaticWebAppWizardContext.ts, src/constants.ts, src/tree/SubscriptionTreeItem.ts, src/utils/settingsUtils.ts, src/utils/workspaceUtils.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/36
Right now, the setting is just being used to set the default value when the prompts come up because I don't want to block users in any way.  But I figured when we have the concept of a basic create, we can auto-populate the value with these settings.
I figured that I should update the setting whenever the user creates the SWA.  Even if they use the default values, I think it makes sense to save it for them to expose the settings.
I think the `apiSubpath` setting should also be set in the case when we create an "api" folder for the user, but that'll be a separate PR.
=> Save defaults after creation of first SWA app

src/commands/createHttpFunction.ts
When creating a Function, use the workspace setting, and fallback on the default `/api` location.
Fixes #107
=> Don't hard-code the API location

src/tree/ActionTreeItem.ts
Turns out the action's payload's id is actually a number, not a string.  Getting rid of the template string was causing an issue-- a compelling case as to why I should be using the API.
=> Force num id to string

package.json, src/commands/browse.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/73
I think the original issue wanted the command names to include "Environment" in them, but I don't think most of the commands would make sense if renamed that way.
I made browse exclusive to environments because I'm trying to really separate the SWA from the environment. 
As for other commands that accept multiple tree items: openInPortal, viewProperties, refresh, etc. the command palette is looking for Static Web Apps because that's what made sense to me (and is the current behavior of other extensions.)
=> Browse 👁‍🗨 selects an environment rather than app

package.json, package.nls.json, src/commands/deleteEnvironment.ts, src/commands/registerCommands.ts, src/tree/EnvironmentTreeItem.ts, src/tree/StaticWebAppTreeItem.ts, src/utils/requestUtils.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/128
I decided to leave the label `Delete...` as is because `Delete Static Web App...` looks terrible.  Maybe I could just shorten it to App or Static App?
I'm using label for Environment's output messages because that's what the user is used to seeing.  The name property is just the build number (that's the name Azure gives it).
Moved the AzureAsyncRequest code to requestUtils, but we should be able to remove this once we move over to the new SDK.
=> Add delete environment

src/commands/createStaticWebApp/ApiLocationStep.ts, src/commands/createStaticWebApp/AppLocationStep.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/170
If a user creates a new repo, we obviously won't have a way to get their remote tree data.  When we allow users to create a new repo with their local git project, we should be able to have a more elegant solution than this, but for now, we can just skip the two location prompts and fallback to the sub-wizards instead (which was the old experience of typing it in).
The step count gets a little wonky after entering a repo name, but it's not too bad and stabilizes after the api location step.
=> Skip Select Location steps if ➕ new repo

src/commands/createHttpFunction.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/185
Relies on https://github.com/microsoft/vscode-azurefunctions/pull/2355/files
I changed `return !(await fse.pathExists(path.join(folderPath, newName));` to `await fse.access(path.join(folderPath, newName));` because access will throw an error if it doesn't exist.  I felt like it made the logic a little simpler rather than doing pathExists, returning it if it's true, if it's false, go into another statement to check if the file exists, then try/catch that and return the result.
=> Add C# and Python 🐍 as supported language triggers

src/utils/gitHubUtils.ts
Co-authored with @johnpapa 
As mentioned in this PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/208, Skip for Now and Manual Enter being at the bottom really hurts users with repos more than 20-30 folders.  Which, since our logic looks into subfolders as well, seems very likely to happen.
I also changed the label for root because it looked so strange to just be a slash.
Before:
After:
=> Move skip/manual enter closer to the top of qp list

src/tree/EnvironmentTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/195
The API now returns source branch as `githubUsername:sourceBranch` for any build that is not the production.  Really strange behavior, but you can see it here
And here on the Portal as well
I don't have any older SWAs with an environment to see if this was a retroactive change or not.  Branch names are not allowed to have a colon though, so my split should be safe.
=> Remove github username from source branch

src/commands/createStaticWebApp/GitHubBranchListStep.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/117
While ideally, we could just create a remote branch for the user, it's a complicated UI experience due to the fact that we can't guarantee that the repo they selected is what they currently have in the local workspace.  GitHub doesn't have an API call to create a new branch (as far as I know) so an error message seems better than nothing.
If anyone knows how to make it more of an error message or change the color of the message/icon, let me know.  I looked through the VS Code API and didn't see anything about it.
Before: 
After:
=> Check for no remote branches

src/tree/EnvironmentTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/228
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/240
The delete bug was caused by passing in the wrong name.  The API wants the name of the static app, not the build.
The refresImpl now updates the data on EnvironmentTreeItem, which is used to determine what the current status is.
=> Fix refreshImpl and delete functions on EnvTreeItems

src/commands/appSettings/downloadAppSettings.ts, src/commands/appSettings/uploadAppSettings.ts, src/commands/createHttpFunction.ts, src/getExtensionApi.ts, src/git.d.ts, tsconfig.json, tslint.json
Refactored from: https://github.com/microsoft/vscode-azurestaticwebapps/pull/246
I need the git api for some other things and thought it would just make code review a little simpler.  While I'm not using the gitApi in the codebase yet, another PR will follow shortly (plus there's #246 if you need an example of how it'll be used)
=> Add git to getExtensionApi file

package.json, src/commands/github/actionCommands.ts, src/tree/ActionTreeItem.ts, src/tree/EnvironmentTreeItem.ts, src/utils/actionUtils.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/173
I don't think there's a great way to fix this through the command palette since `pickTreeItemImpl` can't return an array of children (which I could filter).
=> Remove rerun/cancel from actions that are inProgress/completed

src/commands/createStaticWebApp/createStaticWebApp.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/249
Based off the feedback, I'd like to make it painfully obvious that the action needs to finish before you can access the SWA.  @fiveisprime you might have to help me with the wording of the message a bit though.
I thought it'd help to just reveal the tree item to the user as well so they can see that the action is running.
=> Change msg when creating swa and reveal actions node

package.json, package.nls.json, src/buildPresets/IBuildPreset.ts, src/buildPresets/buildPresets.ts, src/commands/createStaticWebApp/BuildPresetListStep.ts, src/commands/createStaticWebApp/IStaticWebAppWizardContext.ts, src/commands/createStaticWebApp/OutputLocationStep.ts, src/commands/createStaticWebApp/StaticWebAppCreateStep.ts, src/commands/createStaticWebApp/addLocationTelemetry.ts, src/constants.ts, src/tree/SubscriptionTreeItem.ts
As per Mitch's offline email, the yml is now constructed with output_location rather than app_artifact_location so just changing it within the extension to be consistent.  The SDK hasn't updated to reflect this change and they'll keep supporting appArtifactLocation, so we should be good to keep that as-is for now.
=> Changing references to App Artifact to Output Location

package-lock.json, package.json, src/commands/github/actionCommands.ts, src/utils/actionUtils.ts, src/utils/azureUtils.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/172
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/262
I think that this solution mitigates one of our concerns about polling before which was refreshing the tree or tree node was a waste of resources and also distracting.  Also because the frequency of polling gets incrementally longer, if it's a long-running build, it shouldn't impact the user too badly.
Plus I don't see people rerunning too many actions at once anyway.
=> Use retry logic to check status and refresh when workflow completes

package.json
When I changed the context value of ActionTreeItems, the view properties command wasn't showing up for Actions nodes.
=> Action$ to Action so that context menu item for view property shows up

CHANGELOG.md, package-lock.json, package.json, src/extension.ts, src/extensionVariables.ts
Fixes #328 
Retroactively adding the 0.5.1 release changes.
=> Add experimental service from 0.5.1

src/commands/appSettings/AppSettingsClient.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/109
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/235
It looks like keys started adhering to the Linux naming standards.
=> Don't allow special characters in app setting keys

src/constants.ts, src/tree/EnvironmentTreeItem.ts, src/tree/StaticWebAppTreeItem.ts, src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/319
| Old | New |
|-|-|
|![Screen Shot 2021-04-27 at 1 53 35 PM](https://user-images.githubusercontent.com/22795803/116311533-343c5400-a760-11eb-9589-a78b3a3cc22a.png)|![Screen Shot 2021-04-27 at 1 52 58 PM](https://user-images.githubusercontent.com/22795803/116311542-36061780-a760-11eb-8ddc-b25968b1b32b.png)|
The first SWA in this example has been linked to Azure DevOps so the SWA node loads fine but the environment doesn't.
The second SWA hasn't been linked to any version control.
=> Throw better errors if SWA isn't linked to GitHub

src/commands/createRepo/RemoteShortnameStep.ts, src/commands/createStaticWebApp/StaticWebAppNameStep.ts, src/commands/createStaticWebApp/postCreateStaticWebApp.ts, src/commands/createStaticWebApp/setWorkspaceContexts.ts, src/tree/ActionTreeItem.ts, src/tree/ActionsTreeItem.ts, src/tree/EnvironmentTreeItem.ts, src/tree/JobTreeItem.ts, src/tree/StaticWebAppTreeItem.ts, src/utils/gitHubUtils.ts, src/utils/gitUtils.ts
Before this PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/335, there was only gitHubUtils which kind of threw git commands in there as well.  Since I added a gitUtils file, I wanted to refactor some of the functions that were more git specific.
Was also able to delete some GitHub quickpick related code that I forgot to remove.
=> Refactor some gitHub vs git functions

src/commands/createRepo/RepoCreateStep.ts, src/commands/createStaticWebApp/IStaticWebAppWizardContext.ts, src/commands/createStaticWebApp/StaticWebAppNameStep.ts, src/commands/createStaticWebApp/createStaticWebApp.ts
I forgot that there's a lot of repo creation/commit code in the RepoCreate step that I could delete (since we are enforcing it at the beginning now).
RepoData isn't needed anymore either since we'll have the repoHtml.  BranchData is needed since the branch name gets passed up to the SWA platform.
=> Remove more repo create related code

src/commands/appSettings/AppSettingsClient.ts, src/tree/EnvironmentTreeItem.ts, src/tree/FunctionsTreeItem.ts, src/tree/StaticWebAppTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/363
I had to move the treeItem creation further below because it relied on envTreeItem properties that weren't defined yet.
Technically `production` is also a build and it worked fine when I used `listStaticSiteBuildFunctions` (rather than `listStaticSiteFunctions`, but I figured I should change it to use the proper API call in case anything changes in the future.
=> Use build for non-production builds

src/commands/createRepo/RepoNameStep.ts, src/commands/createStaticWebApp/StaticWebAppNameStep.ts, src/tree/SubscriptionTreeItem.ts
I also moved the GitHub repo create steps _after_ resourceList and skuList steps.  It felt like it made more sense to have all the Azure stuff together rather than doing SWA name, GitHub stuff, and then RG and Sku.  
@fiveisprime Let me know if you think this is weird.
=> Swap swa name with github repo name steps

src/commands/createStaticWebApp/ApiLocationStep.ts, src/commands/createStaticWebApp/AppLocationStep.ts, src/commands/createStaticWebApp/OutputLocationStep.ts, src/commands/createStaticWebApp/addLocationTelemetry.ts, src/commands/createStaticWebApp/createStaticWebApp.ts, src/tree/SubscriptionTreeItem.ts
I wanted to add some telemetry on how often workspace settings get used.  I'm seeing a lot of 'non-default' values, but it's very possible that users are just typing their own values.
I wanted to remove the settings from being added since with the current workspace requirements, it'll add the settings silently every time.  I'm thinking maybe we should have a notification or a setting to disable that behavior.  The main downside to it is that it makes the repo dirty and can potentially screw up the `git pull` we do for the workflow file since they're both existing in the .vscode folder.
I'm moving git pull to before the settings getting added for now to help mitigate that problem, but it is still weird to have your repo be "dirty" immediately after creating your SWA.
=> Add telemetry for workspace settings

src/commands/createStaticWebApp/createStaticWebApp.ts, src/utils/gitUtils.ts, src/utils/workspaceUtils.ts
Specifically, there were a lot of gaps for when users were cancelling out of `Create Static Web App` and what users would do if there was no workspace available.
There are also a lot of gaps regarding default branches. We have a lot of instances where we couldn't detect a default branch at all (probably because we weren't looking at remote default branches at all),  but hopefully this should give us a bit more insight.
=> Patch up some telemetry gaps

src/commands/createStaticWebApp/StaticWebAppNameStep.ts, src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/370
Is there a better way to check for `isRelatedName` available?  Maybe this bug fix can wait until after release and I'll just expose `ResourceGroupListStep.getRelatedName`?
=> Fix related name task

src/commands/createStaticWebApp/StaticWebAppNameStep.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/432
Forgot to set the `relatedNameTask` for everything now that I'm properly using it for the resourceGroup name in basic create.
=> Set relatedNameTask for all creation

src/constants.ts, src/extension.ts, src/utils/gitHubUtils.ts
Fixes #450 
Other extensions like GitLens and the GitHub Pull Request extension create menu items in the Accounts activity bar item to notify users to sign in with GitHub.
I verified:
* If a user signs in using this menu, they won't have to sign in again later for our extension.
* The menu item does not show up if the user has signed in with GitHub for SWA.
Example extension showing this feature: https://github.com/microsoft/vscode-extension-samples/tree/main/github-authentication-sample
Relevant lines of code from example extension: https://github.com/microsoft/vscode-extension-samples/blob/d885d442faa3082ceb8f6f182462d17ce7347d6e/github-authentication-sample/src/credentials.ts#L18-L23
=> Add "Sign in with GitHub" item in Accounts activity bar item

src/buildPresets/buildPresets.ts, src/commands/createStaticWebApp/OutputLocationStep.ts, src/constants.ts
This change was suggested last week during standup.
The idea is that the current default `dist/` already breaks most Angular projects if users leave it unchanged. So we're hoping changing it to `dist/<Project name>` helps alert users to change it before deploying.
=> Change Angular output location default

src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/429
I also moved location to be before all the build preset steps because it felt weird to me to do the Azure prompt (the SWA name) and then do all the prompts that also have location in their name, and _then_ do the physical location.
=> Add location to basic create

src/commands/openYAMLConfigFile.ts, src/tree/GitHubConfigGroupTreeItem.ts, src/utils/yamlUtils.ts
Fixes #411 
Clicking on the invalid tree item opens and selects the invalid YAML block.
=> Handle invalid workflow YAML files gracefully

src/commands/createStaticWebApp/createStaticWebApp.ts, src/utils/workspaceUtils.ts
I'd like the detector to check the subfolders one level of depth.  The rationale being that it is likely that users will have their apps/src in a folder besides the root considering a user would normally use this with an api folder.
If anyone has a better idea of the formatting of the telemetry, please let me know!
=> Do detection on subfolders as well

package-lock.json, package.json, package.nls.json, src/commands/cli/getInstalledSwaCliVersion.ts, src/commands/cli/getNewestSwaCliVersion.ts, src/commands/cli/installOrUpdateSwaCli.ts, src/commands/cli/uninstallSwaCli.ts, src/commands/cli/validateSwaCliIsLatest.ts, src/commands/cli/verifyHasNpm.ts, src/commands/registerCommands.ts, src/constants.ts, src/extension.ts, src/utils/settingsUtils.ts
Note: This is prep work for local debugging features which will depend on the SWA CLI.
Add commands:
* Install or Update Azure Static Web Apps CLI
* Uninstall Azure Static Web Apps CLI
Also checks if the installed CLI version is out of date, and notifies the user to update similarly to Functions with func core tools. It will be important to help users get on the latest version of the SWA CLI because we will be depending on new features for local debugging.
Currently only handles global installations of the CLI.
=> Add  install/update and uninstall SWA CLI commands

package-lock.json, package.json, src/commands/createStaticWebApp/createStaticWebApp.ts, src/detectors/node/nodeConstants.ts
I have a hypothesis that most of our users will not have their app project in the root of the workspace, but have multiple subfolders.  Of those subfolders, I want to check if the subfolder has a "src" folder, and if so, if that subfolder is the app build setting that the user provided.
This has no functional change, it should just be checking for the existence of that folder.
=> Add telemetry regarding src folder

README.md
Felt very inspired to fix this
Old:
New:
=> Fix backtick typo in readme

src/debug/StaticWebAppDebugProvider.ts, src/getExtensionApi.ts
If they don't have it installed it'll prompt them to install it.
Fixes: #549
=> Ensure functions is installed when debugging API

src/cli/SwaCliTaskProvider.ts, src/commands/createStaticWebApp/tryGetApiLocations.ts, src/debug/StaticWebAppDebugProvider.ts
Using this in resolve debug config and the task provider because we need to be cautious of long running async calls. And tryGetApiLocation could run for tens of seconds sometimes if we search through a large workspace.
=> Add option to shallow search for api locations

src/debug/StaticWebAppDebugProvider.ts
Option A postfixing both:
Option B: postfixing only the ones picked up from the swa-cli.config.json file
I went with option B because A looked really busy but I'm open to feedback.
=> Add postfix to debug configs

src/debug/StaticWebAppDebugProvider.ts, test/debugProvider.test.ts
Fixes #570 
Fixes issue on slower computers, Chrome might never launch if the emulator takes too long to start.
I've verified this myself using [20211111.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=40798&view=results) on the testers Ubuntu VM.
I'm hardcoding this also because this is easily changed by customizing the launch.json.
edit: Thank you @v-xinda for being so helpful, wouldn't have caught/fixed this without you!
=> Fix Chrome not opening when debugging by increasing the timeout

tsconfig.json
Since this is now closed I think we're safe to turn this off https://github.com/Azure/ms-rest-js/issues/367
=> Remove "skipLIbCheck" from tsconfig

src/detectors/node/NodeDetector.ts, src/tree/ActionTreeItem.ts, src/tree/ActionsTreeItem.ts, src/tree/EnvironmentTreeItem.ts, src/tree/JobTreeItem.ts, src/tree/StepTreeItem.ts, src/tree/WorkflowGroupTreeItem.ts, src/tree/WorkflowTreeItem.ts, src/utils/gitHubUtils.ts, tsconfig.json
Had to make a few types-only changes, most of them are just informing TS that we set `parent` in the super constructor using the `!`.
=> Turn on "strict" tsconfig rule

src/debug/StaticWebAppDebugProvider.ts
Telemetry is showing that this method is being called with lots of `debugConfiguration`s that have no name property. Which is throwing an error when we do `debugConfiguration.name.startsWith`. I was tempted to suppress all telemetry until after that check, but I am afraid I might miss other errors if I did that.
=> Fix error when checking if debug config is SWA

src/cli/SwaCliTaskProvider.ts
In windows,  `SWA: Run my-static-web-apps` failed. 
The console output is as follows.
--run option's value is not recognized correctly.
```
> Executing task: swa start http://localhost:8080  --api-location=http://localhost:7071 --run='npm run serve' --devserver-timeout=90000 <
[run] ''npm' is not recognized as an internal or external command,
[run] operable program or batch file.
[run] cd "C:\my-static-web-apps\" && 'npm exited with code 1
[swa] - Waiting for http://localhost:8080 to be ready
```
I changed single quotes to double quotes in `createSwaCliTask()` in SwaCliTaskProvider.ts, it works fine in windows.
```
> Executing task: swa start http://localhost:8080  --api-location=http://localhost:7071 --run="npm run serve" --devserver-timeout=90000 <
[run] 
[run] > hello@0.1.0 serve …
```
=> Fix single quotes to double quotes for windows

src/commands/appSettings/uploadAppSettings.ts, src/constants.ts, src/vscode-azurefunctions.api.d.ts
Depends on https://github.com/microsoft/vscode-azurefunctions/pull/3032
Fixes #509 
Excludes app settings that have reserved prefixes from being uploaded. 
https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints
=> Handle reserved app settings prefixes

package-lock.json, package.json
The debugging work added in [`v0.9.0`](https://github.com/microsoft/vscode-azurestaticwebapps/releases/tag/v0.9.0) depends on [a fix](https://github.com/microsoft/vscode/issues/135899) that was released in `1.62.1`, now that VS Code is on `1.63.x` we should be good to bump this.
Fixes #579
=> Bump required vscode version to 1.62.1

package-lock.json, package.json
We bumped the vscode version, but forgot to bump the @types version. 
Thanks Nathan for reminding me https://github.com/microsoft/vscode-azurestaticwebapps/pull/602#pullrequestreview-849828770
=> Bump @types/vscode to 1.62.0

src/tree/StaticWebAppTreeItem.ts
Mistakenly changed the behavior to wait when upgrading SDK. This changes it back to match the correct behavior (delete RG in background)
=> Don't wait for resource group to delete after deleting static web app

package-lock.json, package.json, src/tree/ActionsTreeItem.ts
After some investigation, seems like new repos don't support branch as a query param (it returns with an empty array).  I'm not surprised since GitHub itself doesn't have a view to only look at actions based on branch, so I think it makes more sense to just grab all the actions and filter based off the branch instead.
=> Get all workflowruns and filter based off branch

package-lock.json, package.json, src/buildPresets/buildPresets.ts
Closes #612
As @simonaco presents in #612, Next.JS has two ways to create your app: 
1. the standard way, which includes server-side rendering (SSR). This bundles a custom express.js server into your app as an api
2. static export, which doesn't support SSR, and exports as, as the name implies, static html + js + css
We can add these both as different presets to make it easy for users, and I think this would be a good way to show them:
=> Add Next.JS build presets

package-lock.json, package.json, src/commands/cli/validateSwaCliIsLatest.ts
1. This check currently prevents the notification to update the CLI from appearing if the installed version and the newest version don't have the same major version number 🤦 .
2. The logic was most likely [copied from here in Functions](https://github.com/microsoft/vscode-azurefunctions/blob/411ece5f9453af075c1ff48c70aec349f5942a47/src/funcCoreTools/validateFuncCoreToolsIsLatest.ts#L79), and shouldn't be needed for SWA. Func core tools follows a different versioning method, but the SWA CLI follows semver.
3. Should increase the % of users on v1 of the CLI, which will allow us to remove/improve a lot of code.
=> Remove bad semver check to fix CLI update notification

.github/workflows/bump-version-pr.yaml
Triggered when we publish a release on GitHub (can also manually trigger it). Creates a PR [like this one](https://github.com/alexweininger/bumper-test/pull/25) that bumps the prerelease version.
It uses [my own Action task](https://github.com/marketplace/actions/bump-prerelease-version) I published since I couldn't find one that already did what I needed. It has no dependencies.
If we like this, then I'll add it to all the other repos.
=> Add Action to create version bump PR after releasing

src/commands/createHttpFunction.ts
See https://github.com/microsoft/vscode-azurestaticwebapps/issues/735#issuecomment-1276643673 for details. 
[.NET Core 3.1 support is ending December 3, 2022](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#selecting-the-api-language-runtime-version)
=> Remove support for creating .NET Core 3.1 functions

src/commands/createHttpFunction.ts
This will allow users to create .NET 7.0 Functions. However, if they have .NET 6.0 and .NET 7.0 installed locally, then we will still default to .NET 6.0.
Fixes #758
=> Allow creating .NET 7.0 Functions

package-lock.json, package.json
This doesn't really do much of anything right now--since it's still a nested dependency--but this dependency entry is not needed and removing it will be one (tiny) step toward vscode.dev support.
=> Remove spurious dependency

main.js, package-lock.json, package.json, src/IGit.ts, src/RemoteRepoApi.ts, src/commands/createHttpFunction.ts, src/commands/createRepo/RemoteShortnameStep.ts, src/commands/createStaticWebApp/ApiLocationStep.ts, src/commands/createStaticWebApp/AppLocationStep.ts, src/commands/createStaticWebApp/IStaticWebAppWizardContext.ts, src/commands/createStaticWebApp/OutputLocationStep.ts, src/commands/createStaticWebApp/StaticWebAppNameStep.ts, src/commands/createStaticWebApp/createStaticWebApp.ts, src/commands/createStaticWebApp/setWorkspaceContexts.ts, src/commands/createStaticWebApp/tryGetApiLocations.ts, src/commands/createSwaConfigFile.ts, src/commands/github/showActions.ts, src/constants.ts, src/extension.ts, src/extensionVariables.ts, src/getExtensionApi.ts, src/git.d.ts, src/rrapi.d.ts, src/tree/EnvironmentTreeItem.ts, src/tree/WorkflowGroupTreeItem.ts, src/utils/gitHubUtils.ts, src/utils/gitUtils.ts, src/utils/settingsUtils.ts, src/utils/workspaceUtils.ts, webpack.config.js
Remote Repositories lets users open GitHub repos in vscode.dev or in a virtual workspace. By leveraging their API, I was able to basically enable full SWA create support on vscode.dev with minimal refactoring.
There are a lot of files related to the git API, but I will move them in another PR since it would make reviewing changes a pain.
`path.join` won't work in vscode.dev, so I replaced it where relevant. `createHttpFunction` still uses it since it can only be used on desktop, though we can probably just remove it all eventually.
=> Use remote repositories API to enable create static web app in vscode.dev

package.json, src/commands/createSwaConfigFile.ts, src/utils/workspaceUtils.ts
In Web, local directories require special permissions to create files.
We could probably do this for remote repositories, but probably don't have the time for it. It's not super useful without being able to debug anyway.
=> Disable create config

src/constants.ts, src/getExtensionApi.ts, src/utils/gitUtils.ts, src/utils/workspaceUtils.ts
In a web environment, if you had a local workspace opened without a repo (which is always the case in web since we don't have access to their git), the extension tries to use local git to create a new repo which fails. 
This changes it so that it will always prompt the user to open a remote repository.
Honestly, the SWA extension could use a nice refactor. This is definitely something that I will revisit now that I know how webpack works a lot better. The codeflow is also not great to separate into desktop and web right now, so some work will have to be done for that as well.
=> Activate RemoteRepo if local git is disabled. Also always use RemoteRepos for web

src/utils/gitHubUtils.ts
Fixes #827 
Make sure to read https://github.com/microsoft/vscode-azurestaticwebapps/issues/827#issuecomment-1597881084 for context.
Take my explanation with a grain of salt because it's only based on my investigation and assumptions on how browser-based CodeSpaces work. I haven't confirmed any of this with VS Code maintainers.
I believe this is a VS Code bug. I filed https://github.com/microsoft/vscode/issues/185915
---
When connecting to a CodeSpace in your browser you're on a GitHub hosted link and authenticated through GitHub via the "GitHub CodeSpaces" GitHub App. [See your authorized GitHub Apps](https://github.com/settings/apps/authorizations)
In all other scenarios, VS Code uses OAuth to authenticate with GitHub.
When you connect to a CodeSpace in your browser, without taking any …
=> Fix creating SWA in browser CodeSpaces

package-lock.json, package.json
Rather than the latest, this matches the other extensions and was when the newer Node version was first adopted by VS Code.
=> Change minimum VS Code version to 1.82.0

src/commands/createHttpFunction.ts
Adding .NET 8 to the targetFramework as the default for creating HTTP functions since it is now supported in Azure Functions.
Suggested by this comment: https://github.com/microsoft/vscode-azurestaticwebapps/issues/761#issuecomment-1821371282
=> Add and Default .Net8.0 to createHttpFunction targetFramework
